export const COMPONENT_PAGES = [
  { slug: "button", title: "Button", blurb: "Click target with sketchy chrome" },
  { slug: "input", title: "Input", blurb: "Text field with a wobbling border" },
  { slug: "textarea", title: "Textarea", blurb: "Multi-line sketch box" },
  { slug: "checkbox", title: "Checkbox", blurb: "Square plus a drawn check" },
  { slug: "radio", title: "Radio", blurb: "Circle with a hand-filled dot" },
  { slug: "card", title: "Card", blurb: "Container with an optional offset shadow" },
  { slug: "badge", title: "Badge", blurb: "Small tagged label" },
  { slug: "alert", title: "Alert", blurb: "Color-coded callout" },
  { slug: "modal", title: "Modal", blurb: "Radix dialog with sketch framing" },
  { slug: "divider", title: "Divider", blurb: "Squiggly rule, horizontal or vertical" },
  { slug: "progress", title: "Progress", blurb: "Outer bar plus a rougher fill" },
  { slug: "tooltip", title: "Tooltip", blurb: "Radix tooltip in a sketch bubble" },
  { slug: "select", title: "Select", blurb: "Sketchy trigger with a framed menu" },
  { slug: "switch", title: "Switch", blurb: "Pill track and a sliding thumb" },
  { slug: "slider", title: "Slider", blurb: "Wobbly track with a sketch thumb" },
  { slug: "tabs", title: "Tabs", blurb: "Active underline redraws per tab" },
  { slug: "accordion", title: "Accordion", blurb: "Dividers and a rotating chevron" },
  { slug: "table", title: "Table", blurb: "Hand-drawn row rules" },
  { slug: "toast", title: "Toast", blurb: "Sketch card that slides in" },
  { slug: "avatar", title: "Avatar", blurb: "Framed image or initials" },
  { slug: "pagination", title: "Pagination", blurb: "Circled page buttons" },
  { slug: "breadcrumb", title: "Breadcrumb", blurb: "Hand-drawn slash separators" },
  { slug: "skeleton", title: "Skeleton", blurb: "Scribble-fill loading placeholder" },
  { slug: "stepper", title: "Stepper", blurb: "Numbered circles on a sketch path" },
  { slug: "label", title: "Label", blurb: "Typographic caption tied to a field" },
  { slug: "collapsible", title: "Collapsible", blurb: "Single section, chevron rotates open" },
  { slug: "popover", title: "Popover", blurb: "Sketchy floating panel anchored to a trigger" },
  { slug: "dropdown-menu", title: "Dropdown Menu", blurb: "Sketchy menu with hand-drawn separators" },
  { slug: "dialog", title: "Dialog", blurb: "Lighter, composable sibling to Modal" },
  { slug: "alert-dialog", title: "Alert Dialog", blurb: "Confirm/destructive-action prompt" },
  { slug: "command", title: "Command", blurb: "Cmd+K style searchable list, cmdk-powered" },
  { slug: "combobox", title: "Combobox", blurb: "Searchable select — Popover + Command" },
] as const;

export type ComponentSlug = (typeof COMPONENT_PAGES)[number]["slug"];
